name:                nump
version:             0.1.0.0
github:              "githubuser/nump"
license:             BSD3
author:              "Small Hadron Collider"
maintainer:          "mark@smallhadroncollider.com"
copyright:           "2019 Small Hadron Collider"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/nump#readme>

default-extensions:
- OverloadedStrings
- NoImplicitPrelude

dependencies:
- base >= 4.7 && < 5
- classy-prelude

library:
  source-dirs: src
  dependencies:
    - directory

executables:
  nump:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - nump

tests:
  nump-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - nump
    - tasty
    - tasty-hunit
